<?php
namespace Haerriz\GoogleShoppingFeed\Model\Template;

class PresetRegistry
{
    public function getPresets(): array
    {
        return [
            'google' => [
                'name'   => 'Google Shopping',
                'format' => 'xml',
                'mapping' => [
                    ['google_attribute' => 'g:id',                'magento_attribute' => 'sku'],
                    ['google_attribute' => 'g:title',             'magento_attribute' => 'name'],
                    ['google_attribute' => 'g:description',       'magento_attribute' => 'description'],
                    ['google_attribute' => 'g:link',              'magento_attribute' => 'product_url'],
                    ['google_attribute' => 'g:image_link',        'magento_attribute' => 'image_url'],
                    ['google_attribute' => 'g:price',             'magento_attribute' => 'price'],
                    ['google_attribute' => 'g:availability',      'magento_attribute' => 'quantity_and_stock_status'],
                    ['google_attribute' => 'g:condition',         'source_type' => 'static', 'static_value' => 'new'],
                    ['google_attribute' => 'g:brand',             'magento_attribute' => 'manufacturer'],
                    ['google_attribute' => 'g:google_product_category', 'magento_attribute' => 'google_product_category'],
                ],
            ],
            'meta' => [
                'name'   => 'Meta Facebook Catalog',
                'format' => 'csv',
                'mapping' => [
                    ['google_attribute' => 'id',           'magento_attribute' => 'sku'],
                    ['google_attribute' => 'title',        'magento_attribute' => 'name'],
                    ['google_attribute' => 'description',  'magento_attribute' => 'description'],
                    ['google_attribute' => 'availability', 'magento_attribute' => 'quantity_and_stock_status'],
                    ['google_attribute' => 'condition',    'source_type' => 'static', 'static_value' => 'new'],
                    ['google_attribute' => 'price',        'magento_attribute' => 'price'],
                    ['google_attribute' => 'link',         'magento_attribute' => 'product_url'],
                    ['google_attribute' => 'image_link',   'magento_attribute' => 'image_url'],
                    ['google_attribute' => 'brand',        'magento_attribute' => 'manufacturer'],
                ],
            ],
            'instagram' => [
                'name'   => 'Instagram Shopping Catalog',
                'format' => 'csv',
                'mapping' => [
                    ['google_attribute' => 'id',           'magento_attribute' => 'sku'],
                    ['google_attribute' => 'title',        'magento_attribute' => 'name'],
                    ['google_attribute' => 'description',  'magento_attribute' => 'description'],
                    ['google_attribute' => 'availability', 'magento_attribute' => 'quantity_and_stock_status'],
                    ['google_attribute' => 'condition',    'source_type' => 'static', 'static_value' => 'new'],
                    ['google_attribute' => 'price',        'magento_attribute' => 'price'],
                    ['google_attribute' => 'link',         'magento_attribute' => 'product_url'],
                    ['google_attribute' => 'image_link',   'magento_attribute' => 'image_url'],
                    ['google_attribute' => 'brand',        'magento_attribute' => 'manufacturer'],
                ],
            ],
            'snapchat' => [
                'name'   => 'Snapchat Commerce Catalog',
                'format' => 'csv',
                'mapping' => [
                    ['google_attribute' => 'id',           'magento_attribute' => 'sku'],
                    ['google_attribute' => 'title',        'magento_attribute' => 'name'],
                    ['google_attribute' => 'description',  'magento_attribute' => 'description'],
                    ['google_attribute' => 'availability', 'magento_attribute' => 'quantity_and_stock_status'],
                    ['google_attribute' => 'price',        'magento_attribute' => 'price'],
                    ['google_attribute' => 'link',         'magento_attribute' => 'product_url'],
                    ['google_attribute' => 'image_link',   'magento_attribute' => 'image_url'],
                    ['google_attribute' => 'brand',        'magento_attribute' => 'manufacturer'],
                ],
            ],
            'tiktok' => [
                'name'   => 'TikTok Commerce Feed',
                'format' => 'csv',
                'mapping' => [
                    ['google_attribute' => 'sku_id',     'magento_attribute' => 'sku'],
                    ['google_attribute' => 'title',      'magento_attribute' => 'name'],
                    ['google_attribute' => 'description','magento_attribute' => 'description'],
                    ['google_attribute' => 'available_for_sale', 'magento_attribute' => 'quantity_and_stock_status'],
                    ['google_attribute' => 'price',      'magento_attribute' => 'price'],
                    ['google_attribute' => 'url',        'magento_attribute' => 'product_url'],
                    ['google_attribute' => 'image_url',  'magento_attribute' => 'image_url'],
                    ['google_attribute' => 'brand',      'magento_attribute' => 'manufacturer'],
                ],
            ],
            'pinterest' => [
                'name'   => 'Pinterest Catalog Feed',
                'format' => 'csv',
                'mapping' => [
                    ['google_attribute' => 'id',           'magento_attribute' => 'sku'],
                    ['google_attribute' => 'title',        'magento_attribute' => 'name'],
                    ['google_attribute' => 'description',  'magento_attribute' => 'description'],
                    ['google_attribute' => 'availability', 'magento_attribute' => 'quantity_and_stock_status'],
                    ['google_attribute' => 'condition',    'source_type' => 'static', 'static_value' => 'new'],
                    ['google_attribute' => 'price',        'magento_attribute' => 'price'],
                    ['google_attribute' => 'link',         'magento_attribute' => 'product_url'],
                    ['google_attribute' => 'image_link',   'magento_attribute' => 'image_url'],
                    ['google_attribute' => 'google_product_category', 'magento_attribute' => 'google_product_category'],
                ],
            ],
            'microsoft' => [
                'name'   => 'Microsoft Bing Merchant Feed',
                'format' => 'xml',
                'mapping' => [
                    ['google_attribute' => 'g:id',          'magento_attribute' => 'sku'],
                    ['google_attribute' => 'g:title',       'magento_attribute' => 'name'],
                    ['google_attribute' => 'g:description', 'magento_attribute' => 'description'],
                    ['google_attribute' => 'g:link',        'magento_attribute' => 'product_url'],
                    ['google_attribute' => 'g:image_link',  'magento_attribute' => 'image_url'],
                    ['google_attribute' => 'g:price',       'magento_attribute' => 'price'],
                    ['google_attribute' => 'g:availability','magento_attribute' => 'quantity_and_stock_status'],
                    ['google_attribute' => 'g:condition',   'source_type' => 'static', 'static_value' => 'new'],
                    ['google_attribute' => 'g:brand',       'magento_attribute' => 'manufacturer'],
                ],
            ],
            'amazon' => [
                'name'   => 'Amazon Seller Catalog',
                'format' => 'csv',
                'mapping' => [
                    ['google_attribute' => 'item_sku',        'magento_attribute' => 'sku'],
                    ['google_attribute' => 'item_name',       'magento_attribute' => 'name'],
                    ['google_attribute' => 'item_description','magento_attribute' => 'description'],
                    ['google_attribute' => 'price',           'magento_attribute' => 'price'],
                    ['google_attribute' => 'quantity',        'magento_attribute' => 'quantity_and_stock_status'],
                    ['google_attribute' => 'external_product_url', 'magento_attribute' => 'product_url'],
                    ['google_attribute' => 'main_image_url',  'magento_attribute' => 'image_url'],
                    ['google_attribute' => 'brand_name',      'magento_attribute' => 'manufacturer'],
                ],
            ],
            'ebay' => [
                'name'   => 'eBay Inventory Feed',
                'format' => 'csv',
                'mapping' => [
                    ['google_attribute' => 'CustomLabel',  'magento_attribute' => 'sku'],
                    ['google_attribute' => 'Title',        'magento_attribute' => 'name'],
                    ['google_attribute' => 'Description',  'magento_attribute' => 'description'],
                    ['google_attribute' => 'StartPrice',   'magento_attribute' => 'price'],
                    ['google_attribute' => 'Quantity',     'magento_attribute' => 'quantity_and_stock_status'],
                    ['google_attribute' => 'PictureURL',   'magento_attribute' => 'image_url'],
                ],
            ],
            'rakuten' => [
                'name'   => 'Rakuten Advertising Feed',
                'format' => 'csv',
                'mapping' => [
                    ['google_attribute' => 'sku',         'magento_attribute' => 'sku'],
                    ['google_attribute' => 'productname', 'magento_attribute' => 'name'],
                    ['google_attribute' => 'description', 'magento_attribute' => 'description'],
                    ['google_attribute' => 'saleprice',   'magento_attribute' => 'price'],
                    ['google_attribute' => 'producturl',  'magento_attribute' => 'product_url'],
                    ['google_attribute' => 'imageurl',    'magento_attribute' => 'image_url'],
                    ['google_attribute' => 'brand',       'magento_attribute' => 'manufacturer'],
                    ['google_attribute' => 'instock',     'magento_attribute' => 'quantity_and_stock_status'],
                ],
            ],
            'openai' => [
                'name'   => 'OpenAI Agentic Commerce Feed',
                'format' => 'jsonl',
                'mapping' => [
                    ['google_attribute' => 'id',                  'magento_attribute' => 'sku'],
                    ['google_attribute' => 'name',                'magento_attribute' => 'name'],
                    ['google_attribute' => 'description',         'magento_attribute' => 'description'],
                    ['google_attribute' => 'short_description',   'magento_attribute' => 'short_description'],
                    ['google_attribute' => 'price',               'magento_attribute' => 'price'],
                    ['google_attribute' => 'currency',            'source_type' => 'static', 'static_value' => 'INR'],
                    ['google_attribute' => 'availability',        'magento_attribute' => 'quantity_and_stock_status'],
                    ['google_attribute' => 'url',                 'magento_attribute' => 'product_url'],
                    ['google_attribute' => 'image_url',           'magento_attribute' => 'image_url'],
                    ['google_attribute' => 'brand',               'magento_attribute' => 'manufacturer'],
                    ['google_attribute' => 'category',            'magento_attribute' => 'google_product_category'],
                    ['google_attribute' => 'condition',           'source_type' => 'static', 'static_value' => 'new'],
                ],
            ],
        ];
    }
}
